name: Brewski
url: https://github.com/tiaanduplessis/hexo-theme-brewski

menu:
  Home: /
  About: /about
  Archives: /archives
  GitHub: https://github.com/dimkirt
  RSS: https://backend-definite.com/atom.xml

favicon: /favicon.png
logo: /logo.png

# Disqus shortname
disqus:

# Analytics
google_analytics:

# Copyright Infomation
copyright:
  since: 2020
  name: Dimitris Kirtsios
  url: https://backend-definite.com
